"use client";

import { useState, useEffect } from "react";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { ScrollArea } from "./ui/scroll-area";
import { Avatar, AvatarFallback } from "./ui/avatar";
import {
  PanelLeftClose,
  Plus,
  Search,
  MessageSquare,
  MoreVertical,
  Pencil,
  Trash2,
  Archive,
  Pin,
  Settings,
  CreditCard,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "./ui/dialog";
import { toast } from "sonner";
import {
  getConversations,
  searchConversations,
  createConversation,
  deleteConversation,
  archiveConversation,
  pinConversation,
  updateConversation,
  getUsageToday,
  getSubscription,
  getMessageLimit,
} from "@/lib/storage";
import { Conversation } from "@/lib/types";
import { useRouter } from "next/navigation";

interface ConversationSidebarProps {
  activeConversationId: string | null;
  onSelectConversation: (id: string) => void;
  onClose: () => void;
  onRefresh: () => void;
}

export function ConversationSidebar({
  activeConversationId,
  onSelectConversation,
  onClose,
  onRefresh,
}: ConversationSidebarProps) {
  const router = useRouter();
  const [searchQuery, setSearchQuery] = useState("");
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [conversationToDelete, setConversationToDelete] = useState<string | null>(null);
  const [renameDialogOpen, setRenameDialogOpen] = useState(false);
  const [conversationToRename, setConversationToRename] = useState<string | null>(null);
  const [newTitle, setNewTitle] = useState("");

  const loadConversations = () => {
    if (searchQuery) {
      setConversations(searchConversations(searchQuery));
    } else {
      setConversations(getConversations());
    }
  };

  useEffect(() => {
    loadConversations();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchQuery]);

  const handleNewChat = () => {
    const newConv = createConversation();
    onSelectConversation(newConv.id);
    loadConversations();
    onRefresh();
    toast.success("New conversation started!");
  };

  const handleDelete = (id: string) => {
    setConversationToDelete(id);
    setDeleteDialogOpen(true);
  };

  const confirmDelete = () => {
    if (conversationToDelete) {
      deleteConversation(conversationToDelete);
      if (activeConversationId === conversationToDelete) {
        const remaining = getConversations();
        if (remaining.length > 0) {
          onSelectConversation(remaining[0].id);
        } else {
          onSelectConversation(null);
        }
      }
      loadConversations();
      onRefresh();
      toast.success("Conversation deleted");
    }
    setDeleteDialogOpen(false);
    setConversationToDelete(null);
  };

  const handleRename = (id: string, currentTitle: string) => {
    setConversationToRename(id);
    setNewTitle(currentTitle);
    setRenameDialogOpen(true);
  };

  const confirmRename = () => {
    if (conversationToRename && newTitle.trim()) {
      updateConversation(conversationToRename, {
        title: newTitle.trim(),
        autoGeneratedTitle: false,
      });
      loadConversations();
      onRefresh();
      toast.success("Conversation renamed");
    }
    setRenameDialogOpen(false);
    setConversationToRename(null);
    setNewTitle("");
  };

  const handlePin = (id: string, currentPinned: boolean) => {
    pinConversation(id, !currentPinned);
    loadConversations();
    onRefresh();
    toast.success(currentPinned ? "Unpinned" : "Pinned");
  };

  const handleArchive = (id: string) => {
    archiveConversation(id);
    loadConversations();
    onRefresh();
    toast.success("Conversation archived");
  };

  const usage = getUsageToday();
  const subscription = getSubscription();
  const messageLimit = getMessageLimit();
  const usagePercent = messageLimit === Infinity ? 0 : (usage.messageCount / messageLimit) * 100;

  return (
    <div className="h-full flex flex-col bg-white">
      {/* Header */}
      <div className="p-4 border-b border-slate-200">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <Avatar className="w-8 h-8 bg-gradient-to-br from-purple-600 to-pink-600">
              <AvatarFallback className="text-white font-semibold text-sm">AI</AvatarFallback>
            </Avatar>
            <h2 className="font-semibold text-lg">AI Chat</h2>
          </div>
          <div className="flex items-center gap-1">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="w-8 h-8">
                  <Settings className="w-4 h-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem onClick={() => router.push("/pricing")}>
                  <CreditCard className="w-4 h-4 mr-2" />
                  Subscription & Billing
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Settings className="w-4 h-4 mr-2" />
                  Settings
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem className="text-red-600">
                  Sign Out
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <Button variant="ghost" size="icon" className="w-8 h-8" onClick={onClose}>
              <PanelLeftClose className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* New Chat Button */}
        <Button
          onClick={handleNewChat}
          className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white shadow-lg"
        >
          <Plus className="w-4 h-4 mr-2" />
          New Chat
        </Button>
      </div>

      {/* Search */}
      <div className="p-4 border-b border-slate-200">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <Input
            placeholder="Search conversations..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9"
          />
        </div>
      </div>

      {/* Conversation List */}
      <ScrollArea className="flex-1">
        <div className="p-2">
          {conversations.length === 0 ? (
            <div className="text-center py-8 text-slate-500">
              <MessageSquare className="w-12 h-12 mx-auto mb-2 opacity-30" />
              <p className="text-sm">
                {searchQuery ? "No conversations found" : "No conversations yet"}
              </p>
              {!searchQuery && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="mt-2"
                  onClick={handleNewChat}
                >
                  Start your first chat
                </Button>
              )}
            </div>
          ) : (
            conversations.map((conversation) => {
              const timeAgo = getTimeAgo(conversation.lastMessageAt);
              return (
                <div
                  key={conversation.id}
                  onClick={() => onSelectConversation(conversation.id)}
                  className={`group relative p-3 rounded-lg mb-1 cursor-pointer transition-all ${
                    activeConversationId === conversation.id
                      ? "bg-gradient-to-r from-purple-50 to-pink-50 border border-purple-200"
                      : "hover:bg-slate-50"
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        {conversation.isPinned && (
                          <Pin className="w-3 h-3 text-purple-600 fill-purple-600" />
                        )}
                        <h3 className="font-medium text-sm truncate">{conversation.title}</h3>
                      </div>
                      <p className="text-xs text-slate-500">
                        {conversation.messageCount} {conversation.messageCount === 1 ? "message" : "messages"}
                      </p>
                      <span className="text-xs text-slate-400 mt-1 block">
                        {timeAgo}
                      </span>
                    </div>

                    {/* More Options */}
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="w-6 h-6 opacity-0 group-hover:opacity-100 transition-opacity"
                          onClick={(e) => e.stopPropagation()}
                        >
                          <MoreVertical className="w-4 h-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem onClick={() => handleRename(conversation.id, conversation.title)}>
                          <Pencil className="w-4 h-4 mr-2" />
                          Rename
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => handlePin(conversation.id, conversation.isPinned)}>
                          <Pin className="w-4 h-4 mr-2" />
                          {conversation.isPinned ? "Unpin" : "Pin"}
                        </DropdownMenuItem>
                        <DropdownMenuItem onClick={() => handleArchive(conversation.id)}>
                          <Archive className="w-4 h-4 mr-2" />
                          Archive
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem
                          className="text-red-600"
                          onClick={() => handleDelete(conversation.id)}
                        >
                          <Trash2 className="w-4 h-4 mr-2" />
                          Delete
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>
              );
            })
          )}
        </div>
      </ScrollArea>

      {/* Usage Info */}
      <div className="p-4 border-t border-slate-200 bg-slate-50">
        <div className="text-xs text-slate-600 mb-2">
          <div className="flex justify-between mb-1">
            <span>Messages today:</span>
            <span className="font-semibold">
              {usage.messageCount} / {messageLimit === Infinity ? "∞" : messageLimit}
            </span>
          </div>
          {messageLimit !== Infinity && (
            <div className="w-full h-1.5 bg-slate-200 rounded-full overflow-hidden">
              <div
                className={`h-full rounded-full ${
                  usagePercent >= 80
                    ? "bg-gradient-to-r from-red-500 to-orange-500"
                    : "bg-gradient-to-r from-purple-600 to-pink-600"
                }`}
                style={{ width: `${Math.min(usagePercent, 100)}%` }}
              ></div>
            </div>
          )}
        </div>
        {subscription.planType === "free" && (
          <Button
            variant="outline"
            size="sm"
            className="w-full text-xs border-purple-200 hover:bg-purple-50"
            onClick={() => router.push("/pricing")}
          >
            Upgrade to Pro
          </Button>
        )}
      </div>

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Conversation</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete this conversation? This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={confirmDelete}>
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Rename Dialog */}
      <Dialog open={renameDialogOpen} onOpenChange={setRenameDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Rename Conversation</DialogTitle>
            <DialogDescription>
              Enter a new title for this conversation.
            </DialogDescription>
          </DialogHeader>
          <Input
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
            placeholder="Conversation title"
            onKeyDown={(e) => {
              if (e.key === "Enter") confirmRename();
            }}
          />
          <DialogFooter>
            <Button variant="outline" onClick={() => setRenameDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={confirmRename}>Save</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

function getTimeAgo(date: Date): string {
  const now = new Date();
  const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);

  if (seconds < 60) return "Just now";
  if (seconds < 3600) return `${Math.floor(seconds / 60)} min ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)} hours ago`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)} days ago`;
  return date.toLocaleDateString();
}

