export interface Message {
  id: string;
  conversationId: string;
  sender: "user" | "ai";
  content: string;
  timestamp: Date;
  isEdited?: boolean;
  parentMessageId?: string;
  rating?: "up" | "down" | null;
}

export interface Conversation {
  id: string;
  title: string;
  autoGeneratedTitle: boolean;
  createdAt: Date;
  updatedAt: Date;
  lastMessageAt: Date;
  messageCount: number;
  status: "active" | "archived";
  tags: string[];
  isPinned: boolean;
}

export interface UserSubscription {
  planType: "free" | "pro" | "plus";
  status: "active" | "cancelled" | "past_due";
  currentPeriodEnd?: Date;
}

export interface UsageTracking {
  date: string;
  messageCount: number;
  resetAt: Date;
}
